const m=JSON.parse(sessionStorage.getItem('t2_member')||'null');if(!m)location.href='index.html';
const key=x=>'t2_'+x+'_'+m.citizenId;let profile=JSON.parse(localStorage.getItem(key('profile'))||'{}'),contacts=JSON.parse(localStorage.getItem(key('contacts'))||'{}'),beneficiaries=JSON.parse(localStorage.getItem(key('beneficiaries'))||'[]');
const TEST_BILLS=[];
function money(n){return '฿'+Number(n||0).toLocaleString('th-TH')}
function init(){document.getElementById('memberName').textContent=m.firstName+' '+m.lastName;document.getElementById('id4').textContent=m.citizenId.slice(-4);document.getElementById('profileName').value=profile.name||m.firstName+' '+m.lastName;['address','phone','bank','bankAccount'].forEach(x=>document.getElementById(x).value=profile[x]||'');if(profile.photo)document.getElementById('avatar').innerHTML='<img src="'+profile.photo+'">';['c1name','c1relation','c1phone','c2name','c2relation','c2phone'].forEach(x=>document.getElementById(x).value=contacts[x]||'');renderBills();renderBeneficiaries()}
function toggleMemberMenu(){document.getElementById('memberMenu').classList.toggle('open');document.getElementById('memberShade').classList.toggle('show')}
function showPage(id){document.querySelectorAll('.memberPage').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');toggleMemberMenu()}
function renderBills(){let paid=TEST_BILLS.reduce((s,x)=>s+x.amount,0),reward=TEST_BILLS.reduce((s,x)=>s+x.reward,0);document.getElementById('sumPaid').textContent=money(paid);document.getElementById('sumReward').textContent=money(reward);document.getElementById('billCount').textContent=TEST_BILLS.length;const empty='<div class="emptyState"><b>ยังไม่มีรายการชำระเงิน</b><small>เมื่อ Admin บันทึกบิล รายการจะแสดงที่นี่</small></div>';const rows=TEST_BILLS.map(x=>'<div class="billCard"><div><b>'+money(x.amount)+'</b><small>'+x.date+' • '+x.time+'</small></div><div class="billReward">ค่าตอบแทน '+money(x.reward)+'</div></div>').join('');document.getElementById('recentBills').innerHTML=rows||empty;document.getElementById('allBills').innerHTML=rows||empty}
function previewPhoto(input){const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{profile.photo=r.result;document.getElementById('avatar').innerHTML='<img src="'+r.result+'">'};r.readAsDataURL(f)}
function saveProfile(){profile={...profile,name:profileName.value.trim(),address:address.value.trim(),phone:phone.value.trim(),bank:bank.value.trim(),bankAccount:bankAccount.value.trim()};localStorage.setItem(key('profile'),JSON.stringify(profile));profileMsg.innerHTML='<div class="saveOk">บันทึกข้อมูลแล้ว</div>'}
function saveContacts(){contacts={c1name:c1name.value.trim(),c1relation:c1relation.value.trim(),c1phone:c1phone.value.trim(),c2name:c2name.value.trim(),c2relation:c2relation.value.trim(),c2phone:c2phone.value.trim()};if(Object.values(contacts).some(x=>!x)){contactMsg.innerHTML='<div class="warn">กรุณากรอกผู้ติดต่อทั้ง 2 คนให้ครบ</div>';return}localStorage.setItem(key('contacts'),JSON.stringify(contacts));contactMsg.innerHTML='<div class="saveOk">บันทึกผู้ติดต่อแล้ว</div>'}
function addBeneficiary(){beneficiaries.push({name:'',relation:'',phone:''});renderBeneficiaries()}
function removeBeneficiary(i){beneficiaries.splice(i,1);saveBeneficiaries()}
function saveBeneficiaries(){document.querySelectorAll('.beneficiaryCard').forEach((el,i)=>{beneficiaries[i]={name:el.querySelector('.bn').value.trim(),relation:el.querySelector('.br').value.trim(),phone:el.querySelector('.bp').value.trim()}});localStorage.setItem(key('beneficiaries'),JSON.stringify(beneficiaries));renderBeneficiaries()}
function renderBeneficiaries(){beneficiaryList.innerHTML=beneficiaries.length?beneficiaries.map((b,i)=>'<div class="beneficiaryCard"><div class="cardHead"><b>ผู้รับผลประโยชน์ '+(i+1)+'</b><button onclick="removeBeneficiary('+i+')">ลบ</button></div><label>ชื่อ-นามสกุล<input class="bn" value="'+(b.name||'')+'"></label><label>ความสัมพันธ์<input class="br" value="'+(b.relation||'')+'"></label><label>เบอร์โทร<input class="bp" value="'+(b.phone||'')+'"></label></div>').join('')+'<button class="primary" onclick="saveBeneficiaries()">บันทึกผู้รับผลประโยชน์</button>':'<div class="emptyState"><b>ยังไม่มีผู้รับผลประโยชน์</b><small>สามารถเพิ่มได้ไม่จำกัดจำนวน</small></div>'}
function logout(){sessionStorage.removeItem('t2_member');location.href='index.html'}init();