const API_URL='https://script.google.com/macros/s/AKfycbyp18ODOgdhH2R-QdYBeasG2s4817N7vb3w5fA1wED3J2YiY9QLMODcKRnqH7NoZFWd/exec';
const m=JSON.parse(sessionStorage.getItem('t2_member')||'null');if(!m||!m.token)location.href='index.html';
const key=x=>'t2_'+x+'_'+m.citizenId;let profile=JSON.parse(localStorage.getItem(key('profile'))||'{}'),beneficiaries=JSON.parse(localStorage.getItem(key('beneficiaries'))||'[]'),contacts=JSON.parse(localStorage.getItem(key('othercontacts'))||'[]'),BILLS=[];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function money(n){return '฿'+Number(n||0).toLocaleString('th-TH')}function name(){return m.firstName+' '+m.lastName}
async function api(action,data={}){const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token:m.token,...data})});return r.json()}
async function init(){id4.textContent=m.citizenId.slice(-4);fillEdit();renderProfile();renderBeneficiaries();renderContacts();try{const s=await api('checkSession');if(!s.ok){logout();return}await loadBills()}catch(e){allBills.innerHTML='<div class="warn">เชื่อมต่อรายการชำระเงินไม่ได้ กรุณาลองใหม่</div>'}}
function toggleMemberMenu(){memberMenu.classList.toggle('open');memberShade.classList.toggle('show')}function showPage(id){document.querySelectorAll('.memberPage').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');toggleMemberMenu();if(id==='payments')loadBills()}
function fillEdit(){firstName.value=m.firstName;lastName.value=m.lastName;firstName.readOnly=true;lastName.readOnly=true;citizenId.value=m.citizenId;phone.value=profile.phone||'';email.value=profile.email||'';bank.value=profile.bank||'';bankAccount.value=profile.bankAccount||'';if(profile.photo){editAvatar.innerHTML='<img src="'+profile.photo+'">';avatar.innerHTML='<img src="'+profile.photo+'">'}}
function renderProfile(){displayName.textContent=name();profileView.innerHTML='<div class="profileInfo"><div><small>ชื่อ-นามสกุล</small><b>'+esc(name())+'</b></div><div><small>เลขบัตรประชาชน</small><b>•••••••••'+esc(m.citizenId.slice(-4))+'</b></div><div><small>เบอร์โทรศัพท์</small><b>'+(esc(profile.phone)||'—')+'</b></div><div><small>อีเมล</small><b>'+(esc(profile.email)||'—')+'</b></div><div><small>บัญชี</small><b>'+(profile.bank?esc(profile.bank)+' • '+esc(profile.bankAccount):'—')+'</b></div></div>'}
function setEdit(v){profileView.classList.toggle('hidden',v);profileEdit.classList.toggle('hidden',!v);if(v)fillEdit()}
function previewPhoto(input){const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{profile.photo=r.result;editAvatar.innerHTML='<img src="'+r.result+'">';avatar.innerHTML='<img src="'+r.result+'">'};r.readAsDataURL(f)}
function saveProfile(){profile={...profile,phone:phone.value.trim(),email:email.value.trim(),bank:bank.value.trim(),bankAccount:bankAccount.value.trim()};localStorage.setItem(key('profile'),JSON.stringify(profile));renderProfile();setEdit(false)}
function addBeneficiary(){beneficiaries.push({firstName:'',lastName:'',phone:'',citizenId:'',percent:''});renderBeneficiaries()}function removeBeneficiary(i){beneficiaries.splice(i,1);saveBeneficiaries()}
function saveBeneficiaries(){document.querySelectorAll('.beneficiaryCard:not(.contactCard)').forEach((e,i)=>beneficiaries[i]={firstName:e.querySelector('.bf').value.trim(),lastName:e.querySelector('.bl').value.trim(),phone:e.querySelector('.bp').value.trim(),citizenId:e.querySelector('.bi').value.trim(),percent:e.querySelector('.pct').value.trim()});localStorage.setItem(key('beneficiaries'),JSON.stringify(beneficiaries));renderBeneficiaries()}
function renderBeneficiaries(){beneficiaryList.innerHTML=beneficiaries.map((b,i)=>'<div class="beneficiaryCard"><div class="cardHead"><b>ผู้รับผลประโยชน์ '+(i+1)+'</b><button onclick="removeBeneficiary('+i+')">ลบ</button></div><div class="twoCol"><label>ชื่อ<input class="bf" value="'+esc(b.firstName)+'"></label><label>นามสกุล<input class="bl" value="'+esc(b.lastName)+'"></label></div><label>เบอร์โทรศัพท์<input class="bp" value="'+esc(b.phone)+'"></label><label>เลขบัตรประชาชน<input class="bi" maxlength="13" value="'+esc(b.citizenId)+'"></label><label>ผลประโยชน์ (%)<input class="pct" type="number" min="0" max="100" value="'+esc(b.percent)+'"></label></div>').join('');if(beneficiaries.length)beneficiaryList.innerHTML+='<button class="primary" onclick="saveBeneficiaries()">บันทึกผู้รับผลประโยชน์</button>'}
function addContact(){contacts.push({firstName:'',lastName:'',phone:''});renderContacts()}function removeContact(i){contacts.splice(i,1);saveContacts()}
function saveContacts(){document.querySelectorAll('.contactCard').forEach((e,i)=>contacts[i]={firstName:e.querySelector('.cf').value.trim(),lastName:e.querySelector('.cl').value.trim(),phone:e.querySelector('.cp').value.trim()});localStorage.setItem(key('othercontacts'),JSON.stringify(contacts));renderContacts()}
function renderContacts(){contactList.innerHTML=contacts.map((c,i)=>'<div class="beneficiaryCard contactCard"><div class="cardHead"><b>บุคคลติดต่อ '+(i+1)+'</b><button onclick="removeContact('+i+')">ลบ</button></div><div class="twoCol"><label>ชื่อ<input class="cf" value="'+esc(c.firstName)+'"></label><label>นามสกุล<input class="cl" value="'+esc(c.lastName)+'"></label></div><label>เบอร์โทรศัพท์<input class="cp" value="'+esc(c.phone)+'"></label></div>').join('');if(contacts.length)contactList.innerHTML+='<button class="primary" onclick="saveContacts()">บันทึกบุคคลติดต่อ</button>'}
async function loadBills(){allBills.innerHTML='<div class="info">กำลังโหลดรายการ...</div>';const d=await api('getMyPayments');if(!d.ok){allBills.innerHTML='<div class="warn">ไม่สามารถโหลดรายการได้</div>';return}BILLS=d.items||d.payments||[];renderBills()}
function renderBills(){const paid=BILLS.reduce((s,x)=>s+Number(x.amount||0),0),reward=BILLS.reduce((s,x)=>s+Number(x.promoReturn||x.reward||0),0);sumPaid.textContent=profileInvestment.textContent=money(paid);sumReward.textContent=profileReward.textContent=money(reward);billCount.textContent=BILLS.length;profileBillCount.textContent=BILLS.length+' รายการ';allBills.innerHTML=BILLS.length?BILLS.map(x=>{const id=x.paymentId||x.payment_id||x.id,status=x.reviewStatus||x.review_status||'pending',done=status!=='pending'&&status!=='รอตรวจทาน'&&status!=='';return '<div class="billCard reviewBill"><div><b>'+money(x.amount)+'</b><small>'+(x.transferDate||x.transfer_date||x.date||'')+' '+(x.transferTime||x.transfer_time||x.time||'')+' • Ref '+esc(x.referenceNo||x.reference_no||x.reference||'')+'</small><small>ผลตอบแทน '+money(x.promoReturn||x.promo_return||x.reward||0)+'</small></div><div class="reviewArea">'+(done?'<span class="reviewDone">'+esc(status)+'</span>':'<button class="reviewOk" onclick="reviewPayment(\''+esc(id)+'\',\'confirmed\')">ข้อมูลถูกต้อง</button><button class="reviewBad" onclick="reviewIncorrect(\''+esc(id)+'\')">แจ้งข้อมูลไม่ถูกต้อง</button>')+'</div></div>'}).join(''):'<div class="emptyState"><b>ยังไม่มีรายการชำระเงิน</b><small>เมื่อ Admin บันทึกรายการที่ยืนยันแล้ว จะแสดงที่นี่</small></div>'}
async function reviewPayment(paymentId,reviewStatus,note=''){try{const d=await api('reviewPayment',{paymentId,reviewStatus,memberNote:note});if(!d.ok){alert(d.message||'บันทึกสถานะไม่สำเร็จ');return}await loadBills()}catch(e){alert('เชื่อมต่อระบบไม่ได้')}}
function reviewIncorrect(id){const note=prompt('กรุณาระบุข้อมูลที่ไม่ถูกต้อง');if(note===null)return;if(!note.trim()){alert('กรุณาระบุรายละเอียด');return}reviewPayment(id,'incorrect',note.trim())}
function logout(){sessionStorage.removeItem('t2_member');location.href='index.html'}init();